# Creating a Pandas Series

In [1]:
import pandas as pd
import numpy as np

In [2]:
labels=["a","b","c"]
my_list=[10,20,30]
arr=np.array([10,20,30])
d={"a":10,"b":20,"c":30}

In [3]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series([10,20,30])

0    10
1    20
2    30
dtype: int64

In [5]:
arr

array([10, 20, 30])

In [6]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [7]:
pd.Series(data=arr,index=labels)

a    10
b    20
c    30
dtype: int32

# Using Dictionaries

In [8]:
d

{'a': 10, 'b': 20, 'c': 30}

In [9]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(data=d,index=["q","c","y"])

q     NaN
c    30.0
y     NaN
dtype: float64

# Using Scalar Value

In [11]:
pd.Series(data="Fiona")

0    Fiona
dtype: object

In [12]:
pd.Series(data="Fiona",index=range(3))

0    Fiona
1    Fiona
2    Fiona
dtype: object

In [13]:
pd.Series(data=10,index=["a","b","c"])

a    10
b    10
c    10
dtype: int64

# Data in a Series

In [14]:
pd.Series([set,list,dict])

0     <class 'set'>
1    <class 'list'>
2    <class 'dict'>
dtype: object

In [17]:
pd.Series(set)[0]([2,5,7,5,8,2])

{2, 5, 7, 8}

In [19]:
pd.Series(list)[0]([2,2,2,2,2,2])

[2, 2, 2, 2, 2, 2]

In [23]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [24]:
pd.Series([sum,print,len])[1]("a")

a


In [25]:
pd.Series([sum,print,len])[2]("apple")

5

In [29]:
pd.Series([sum,print,len])[0]([2,4,4,5])

15

In [30]:
mix_data=["Ferit",2,True]

In [32]:
mix_data

['Ferit', 2, True]

In [33]:
ser=pd.Series(mix_data)
ser

0    Ferit
1        2
2     True
dtype: object

In [34]:
ser.dtype

dtype('O')

In [35]:
type(ser)

pandas.core.series.Series

In [36]:
ser.size

3

In [39]:
type(ser[0])

str

In [40]:
type(ser[1])

int

In [41]:
type(ser[2])

bool

In [42]:
arr=np.array(mix_data)
arr

array(['Ferit', '2', 'True'], dtype='<U11')

In [43]:
type(arr)

numpy.ndarray

In [44]:
type(arr[1])

numpy.str_

# BASIC ATTRIBUTES & METHODS OF SERIES

In [45]:
ser=pd.Series(np.random.randint(0,100,7))
ser

0    64
1    70
2    89
3    92
4    71
5    89
6    52
dtype: int32

In [46]:
type(ser)

pandas.core.series.Series

In [47]:
ser.dtype

dtype('int32')

In [48]:
ser.shape

(7,)

In [49]:
ser.size

7

In [50]:
len(ser)

7

In [51]:
ser.ndim

1

In [52]:
ser

0    64
1    70
2    89
3    92
4    71
5    89
6    52
dtype: int32

In [53]:
ser.index

RangeIndex(start=0, stop=7, step=1)

In [54]:
ser.keys()

RangeIndex(start=0, stop=7, step=1)

In [55]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [56]:
for i in ser.index:
    print(i)

0
1
2
3
4
5
6


In [60]:
ser.values

array([64, 70, 89, 92, 71, 89, 52])

In [61]:
[i for i in ser.values]

[64, 70, 89, 92, 71, 89, 52]

In [62]:
for i in ser.values:
    print(i)

64
70
89
92
71
89
52


In [63]:
ser.items

<bound method Series.items of 0    64
1    70
2    89
3    92
4    71
5    89
6    52
dtype: int32>

In [65]:
ser.items()

In [66]:
list(ser.items())

[(0, 64), (1, 70), (2, 89), (3, 92), (4, 71), (5, 89), (6, 52)]

In [68]:
for index ,value in ser.items():
    print(f"index: {index}, value:{value}")

index: 0, value:64
index: 1, value:70
index: 2, value:89
index: 3, value:92
index: 4, value:71
index: 5, value:89
index: 6, value:52


In [69]:
ser=pd.Series(data=np.random.randint(0,25,10),index= [i for i in "cbaefdgihj"])

In [70]:
ser

c    13
b     5
a     4
e     9
f    17
d    11
g     1
i     0
h    17
j     0
dtype: int32

In [71]:
ser.head()

c    13
b     5
a     4
e     9
f    17
dtype: int32

In [72]:
ser.tail()

d    11
g     1
i     0
h    17
j     0
dtype: int32

In [74]:
ser.sample()

h    17
dtype: int32

In [75]:
ser.sort_index(ascending=True)

a     4
b     5
c    13
d    11
e     9
f    17
g     1
h    17
i     0
j     0
dtype: int32

In [76]:
ser.sort_values(ascending=True)

i     0
j     0
g     1
a     4
b     5
e     9
d    11
c    13
f    17
h    17
dtype: int32

In [77]:
ser

c    13
b     5
a     4
e     9
f    17
d    11
g     1
i     0
h    17
j     0
dtype: int32

In [78]:
ser.isin([5,6])

c    False
b     True
a    False
e    False
f    False
d    False
g    False
i    False
h    False
j    False
dtype: bool

# Indexing and Slicing with Pandas Series



Bir Diziyi kullanmanın anahtarı dizinini anlamaktır. Pandalar, bilgilerin hızlı bir şekilde aranmasına izin vererek bu dizin adlarını veya numaralarını kullanır.

Pandas nesnelerindeki eksen etiketleme bilgileri birçok amaca hizmet eder:

    Analiz, görselleştirme ve etkileşimli konsol ekranı için önemli olan bilinen göstergeleri kullanarak verileri tanımlar (yani meta verileri sağlar).
    
    Otomatik ve açık veri hizalamayı etkinleştirir.
    
    Veri kümesinin alt kümelerinin sezgisel olarak alınmasına ve ayarlanmasına olanak tanır.
    

In [79]:
ser1 = pd.Series([1,2,3,4], index=["USA","Germany","RF","Japan"]) 
ser2=pd.Series([1,2,5,4,6], index=["USA","Germany","Italy","Japan","Spain"])

In [80]:
ser1

USA        1
Germany    2
RF         3
Japan      4
dtype: int64

In [81]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
Spain      6
dtype: int64

In [84]:
ser1.sort_index()

Germany    2
Japan      4
RF         3
USA        1
dtype: int64

In [85]:
ser1.sort_values()

USA        1
Germany    2
RF         3
Japan      4
dtype: int64

In [86]:
ser1

USA        1
Germany    2
RF         3
Japan      4
dtype: int64

In [87]:
ser1[3]

4

In [88]:
ser1.index[1]

'Germany'

In [89]:
ser1.index.get_loc("Japan")

3

In [90]:
ser1["Japan"]

4

In [92]:
ser1.Japan

4

In [94]:
print("The value for 'Japan' :", ser1["Japan"])

The value for 'Japan' : 4


In [95]:
print("The value for the 3rd index: ", ser1[3])

The value for the 3rd index:  4


In [96]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
Spain      6
dtype: int64

In [97]:
ser2[0]

1

In [98]:
ser2["USA"]

1

In [99]:
ser2[2:]

Italy    5
Japan    4
Spain    6
dtype: int64

In [100]:
ser2[::-1]

Spain      6
Japan      4
Italy      5
Germany    2
USA        1
dtype: int64

In [101]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
RF         NaN
Spain      NaN
USA        2.0
dtype: float64

In [102]:
ser1*ser2 


Germany     4.0
Italy       NaN
Japan      16.0
RF          NaN
Spain       NaN
USA         1.0
dtype: float64

In [103]:
ser=pd.Series(data=[121,200,150,99], index=["terry","micheal","orion","jason"])
ser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [104]:
ser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [106]:
ser["terry"]

121

In [107]:
ser[0]

121

In [108]:
ser[[0,2]]

terry    121
orion    150
dtype: int64

In [109]:
ser[["terry","orion"]]

terry    121
orion    150
dtype: int64

In [110]:
ser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

In [111]:
ser["terry":"orion"]

terry      121
micheal    200
orion      150
dtype: int64

# Selection with Condition and Broadcasting

In [112]:
ser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [113]:
"terry" in ser

True

In [114]:
"bob" in ser

False

In [115]:
55 in ser.values

False

In [116]:
121 in ser.values

True

In [117]:
ser < 100

terry      False
micheal    False
orion      False
jason       True
dtype: bool

In [120]:
ser[ser < 100] =100
ser

terry      121
micheal    200
orion      150
jason      100
dtype: int64

In [121]:
ser.isin([121])

terry       True
micheal    False
orion      False
jason      False
dtype: bool

In [122]:
ser[ser.isin([121])]=125

In [123]:
ser

terry      125
micheal    200
orion      150
jason      100
dtype: int64

# Recap for Several Selecting Attributes

In [124]:
ser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [125]:
ser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [126]:
ser.values

array([125, 200, 150, 100], dtype=int64)

In [129]:
ser.items

<bound method Series.items of terry      125
micheal    200
orion      150
jason      100
dtype: int64>

In [130]:
ser.items()

In [131]:
list(ser.items())

[('terry', 125), ('micheal', 200), ('orion', 150), ('jason', 100)]

In [132]:
for index,value in ser.items():
    print(index,value)

terry 125
micheal 200
orion 150
jason 100


In [133]:
ser

terry      125
micheal    200
orion      150
jason      100
dtype: int64

In [134]:
ser.sort_index(ascending=False)

terry      125
orion      150
micheal    200
jason      100
dtype: int64

In [135]:
ser.sort_values(ascending=False)

micheal    200
orion      150
terry      125
jason      100
dtype: int64

In [136]:
ser.sort_values(ascending=True)

jason      100
terry      125
orion      150
micheal    200
dtype: int64