# Numpy vs Python 
What are Advantages of NumPy Arrays over Regular Python Lists?

Arrays: are used to store homogeneous data (same data type) of fixed size storing in sequential order in memory
    
Lists are used to store data of growing in size and storing this data in available place anywhere(not sequential) in the memory.


#1.) Move Powerful Slicing and Broadcasting functionality

In [2]:
import numpy as np


In [3]:
l=list(range(10))
l[::2]=999
print(l)

#hata verir çünkü bu haliyle iterable değil

TypeError: must assign iterable to extended slice

In [ ]:
a=np.arange(10)
a[::2]=999
print(a)

#oluşan dizideki her bir elemente 999 sayısını eklemek istemiş

In [4]:
a=np.arange(16)
a=a.reshape((4,4))
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [5]:
b=np.arange(25)
b=b.reshape((5,5))
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [6]:
c=np.arange(24)
c=c.reshape((3,8))
print(c)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [7]:
c=c.reshape((4,6))
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [8]:
c[:3:2]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17]])

In [9]:
b[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

2.) Moe Effitient data representation

numpy array are much faster to access and create while having a smaller memory footprint

In [10]:
x=[1,2,3,4,5,6,7,8,9,10]
y=np.array(x)

print(x)
print(y)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
import sys

In [12]:
print(sys.getsizeof(x))

#memoryde kapladıkları alanı öğrenmiş olduk


136


In [13]:
print(sys.getsizeof(y))

#memory de   kapladığı alanı öğrenmiş olduk


144


3.) More Convenient

In [14]:
import time

In [15]:
a=[1,2,3,4]
b=[2,3,4,5]

In [16]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [17]:
ab=[]
for i in range(0,len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

Yukarıdaki numpy kullanmadan yaptığımız uzun liste çarpım işlemi

Aşağıda numpy kullanırsak bir liste için yapılan dört işlemin nasıl yapıldığını göreceğiz.

In [18]:
a1=np.array(a)
b1=np.array(b)

In [19]:
a1*b1

array([ 2,  6, 12, 20])

In [20]:
x1=np.array([1,2,3,4])
y1=np.array([5,6,7,8])


In [21]:
y1*x1

array([ 5, 12, 21, 32])

In [22]:
y1

array([5, 6, 7, 8])

In [23]:
x1

array([1, 2, 3, 4])

In [24]:
a1=np.array([[1,2,3,4],[1,2,3,4],[2,3,4,5]])
b1=np.array([[2,3,4,5],[1,2,3,4],[1,2,3,6]])

In [25]:
a1*b1

array([[ 2,  6, 12, 20],
       [ 1,  4,  9, 16],
       [ 2,  6, 12, 30]])

In [26]:
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [27]:
b1

array([[2, 3, 4, 5],
       [1, 2, 3, 4],
       [1, 2, 3, 6]])

# Built in Function

# 1.)arange()

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [31]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [32]:
range(0,10,2)

range(0, 10, 2)

In [33]:
for i in range(0,10,2):
    print(i)

0
2
4
6
8


In [34]:
for i in range(0,10,3):
    print(i)

0
3
6
9


In [35]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

# 2.)linspace()

np.linspace(start,stop,num=50)

In [36]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [37]:
np.arange(0,11,5)

array([ 0,  5, 10])

In [38]:
np.linspace(0,11,5)

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [39]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [40]:
np.linspace(0,10)

#default olarak 50 tane sayı üretiyor

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [41]:
np.linspace(0,10,51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [42]:
np.linspace(0,10,51,dtype="int")

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

In [43]:
set(np.linspace(0,10,51,dtype="int"))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [44]:
np.linspace(0,[10,20],5,axis=1)

#iki tane linspace oluştur demek 
#biri 0-10 arasında diğeri 0-20 arasında olsun
#5 parçaya böl axis=1 e göre

array([[ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  5. , 10. , 15. , 20. ]])

In [45]:
np.linspace(0,[10,20],5,axis=0)

array([[ 0. ,  0. ],
       [ 2.5,  5. ],
       [ 5. , 10. ],
       [ 7.5, 15. ],
       [10. , 20. ]])

# 3.)"zeros", "ones" & "full

Generate arrays of zeros or ones

np.zeros(shape, dtype=float, order='C')

np.ones(shape, dtype=None, order='C')

np.full(shape, fill_value, dtype=None, order='C')



In [46]:
np.zeros(3)

array([0., 0., 0.])

In [47]:
np.zeros(3,dtype="int")

array([0, 0, 0])

In [48]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.zeros((4,4), dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [50]:
np.ones((4,4),dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [51]:
np.ones(3)

array([1., 1., 1.])

In [52]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [53]:
np.ones((4,4),dtype=str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [54]:
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [55]:
np.full((3,3),"3")

array([['3', '3', '3'],
       ['3', '3', '3'],
       ['3', '3', '3']], dtype='<U1')

In [56]:
np.full((3,3),"htc")

array([['htc', 'htc', 'htc'],
       ['htc', 'htc', 'htc'],
       ['htc', 'htc', 'htc']], dtype='<U3')

In [57]:
np.full((2,4,3),255)

#dept,height,weight

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]])

# 4.)eye()

In [58]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [60]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# Random Built in Methods

# 1.) rand()

In [62]:
np.random.rand()

0.2524037086709142

In [63]:
np.random.rand(3)

array([0.04921994, 0.39474692, 0.95544301])

In [64]:
np.random.rand(3,3)

array([[0.11733203, 0.52305702, 0.37309373],
       [0.48420747, 0.64725792, 0.85857671],
       [0.12816003, 0.81273211, 0.6248312 ]])

In [65]:
np.random.rand((4,4),dtype="int")

TypeError: rand() got an unexpected keyword argument 'dtype'

# 2.)randn()

In [66]:
np.random.randn()

-0.8467668989408752

In [67]:
np.random.randn(2)

array([-0.71917243,  0.2570154 ])

In [68]:
np.random.randn(2,2)

array([[-1.14419005, -1.05859735],
       [-1.35950302,  0.33438085]])

In [69]:
np.random.randn(3,4)

array([[ 0.57192949, -0.89723341,  1.5718907 ,  2.37101719],
       [-0.57676755, -1.19361631, -0.10440221, -1.33530032],
       [ 0.24223052, -0.42490656, -1.7174335 ,  0.74491645]])

In [70]:
np.random.randn(3,4).mean()

0.09505349413929165

In [71]:
np.random.randn(5555).std()

0.9921677864418029

# 3.)randint()

In [72]:
np.random.randint()

TypeError: randint() takes at least 1 positional argument (0 given)

In [73]:
np.random.randint(2)

0

In [74]:
np.random.randint(4)

1

In [75]:

np.random.randint(3,67)

28

In [76]:
np.random.randint(2,56,3)

array([47, 36, 32])

In [77]:
np.random.randint(3,45,68)

array([44, 13, 23, 28, 12,  8, 23, 11, 12, 31,  4, 19, 23, 13, 14, 10, 14,
       18, 15,  9,  3, 11,  5,  8, 31,  7, 32,  5, 21, 14, 28, 12, 29, 32,
       15, 26, 37, 29, 41, 38, 26, 11, 17, 22, 26,  6, 10, 23, 18, 41,  7,
       44, 23,  3, 31, 28, 22, 27, 37, 16,  3, 37, 37,  6, 13, 33,  8,  6])

In [78]:
np.random.randint(10,size=10)

array([6, 4, 4, 1, 5, 6, 3, 6, 5, 9])

In [79]:
np.random.randint(5,size=(3,4))

array([[2, 1, 0, 2],
       [1, 1, 4, 4],
       [2, 3, 0, 3]])

In [80]:
np.random.randint(3,45,size=(5,5))

array([[ 4, 17, 11, 43, 40],
       [20, 41, 36, 41,  8],
       [18,  8,  5, 36, 16],
       [12,  6, 20, 34,  8],
       [43, 44, 13, 16,  7]])

In [81]:
np.random.randint(1,[3,50,100])

array([ 1,  5, 62])

In [82]:
np.random.randint(1,[3,50,100],size=(5,3))

array([[ 2, 39, 96],
       [ 1, 23, 94],
       [ 2, 19, 11],
       [ 1, 43, 58],
       [ 2, 32,  8]])

In [83]:
np.random.randint([1,30,70],[10,40,80],size=(4,3))

array([[ 6, 32, 78],
       [ 6, 39, 79],
       [ 5, 38, 72],
       [ 7, 32, 73]])

# 

# ARRAY ATTRIBUTES & METHODS

In [84]:
arr = np.arange(36)
rand_arr = np.random.randint(0, 50, 10)

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [86]:
rand_arr

array([20, 23, 13,  1, 26, 16, 11, 48, 17, 10])

# reshape

In [87]:
arr.shape

(36,)

In [88]:
arr.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [89]:
arr.reshape(1,36)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35]])

In [90]:
arr.reshape(36,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35]])

In [91]:
arr.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [92]:
arr.reshape(1,4,9)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]]])

In [93]:
arr.reshape(3,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

# "max", "min", "argmax" & "argmin"

In [94]:
rand_arr

array([20, 23, 13,  1, 26, 16, 11, 48, 17, 10])

In [95]:
rand_arr.max()

48

In [96]:
rand_arr.min()

1

In [97]:
rand_arr.mean()

18.5

In [98]:
rand_arr.argmax()

7

In [99]:
rand_arr.argmin()

3

In [100]:
rand_arr_new=rand_arr.reshape(2,5)

In [101]:
rand_arr_new

array([[20, 23, 13,  1, 26],
       [16, 11, 48, 17, 10]])

In [102]:
rand_arr_new.argmin()

3

In [103]:
rand_arr_new.argmax()

7

# SOME OTHER ATTRIBUTES


shape: tuple of array dimensions.

size: Number of elements in the array.

ndim: number of array dimensions.

itemsize: the size in bytes of each element of the array.

dtype: data types of the array.


# shape

In [104]:
arr.shape

(36,)

In [105]:
arr.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [106]:
arr.shape

(36,)

In [107]:
a=arr.reshape(6,6)
a.shape

(6, 6)

# "dtype"

In [108]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [109]:
arr.dtype

dtype('int32')

In [110]:
type(arr)

numpy.ndarray

In [111]:
type(arr[1])

numpy.int32

In [112]:
b=np.full((4,6),2.2)
b

array([[2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2]])

In [113]:
b.dtype

dtype('float64')

In [114]:
ornek=np.arange(10)

In [115]:
ornek

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
ornek.dtype

dtype('int32')

In [117]:
type(ornek)

numpy.ndarray

In [118]:
a=[2,2,2,2]

In [119]:
type(a)

list

# "ndim"

In [120]:
arr.ndim

1

In [121]:
arr.shape

(36,)

In [122]:
b.ndim

2

In [123]:
b.shape

(4, 6)

# size

In [124]:
arr.size

36

In [125]:
len(arr)

36

In [126]:
b=np.random.randint(10,size=(3,5))

In [127]:
b

array([[0, 3, 2, 0, 2],
       [0, 1, 6, 6, 6],
       [9, 8, 3, 0, 6]])

In [128]:
b.ndim

2

In [129]:
b.shape

(3, 5)

In [130]:
b.size

15

In [131]:
len(b)

3

In [132]:
b.itemsize

4

# Comparing list and array by size

array ve listelerin ne kadar hafıza tutuğuna iyi bir örnek :

In [133]:
l=range(1000)

print("size of one item in list :", sys.getsizeof(5))
print("size of all items in list :",sys.getsizeof(5)*len(l))

print("-----"*10)

a=np.arange(1000)

print("size of one item in array :", a.itemsize)
print("size of one item in list :", a.itemsize * a.size)



size of one item in list : 28
size of all items in list : 28000
--------------------------------------------------
size of one item in array : 4
size of one item in list : 4000


# Comparing list and array by computation time 

işlem hacmi arttıça array in üstünlüğü list e göre artar 

In [134]:
size=1000000

l1=range(size)
l2=range(size)

a1=np.array(size)
a2=np.array(size)

#python list

start = time.time()
result = [(x + y) for x, y in zip(l1, l2)]
print("python list took: ", (time.time()-start) * 1000)

# numpy array
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start) * 1000)

python list took:  235.57519912719727
numpy took:  22.939205169677734


# Concatenation of the Arrays

In [135]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.array([7,8,9])

In [136]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [137]:
np.concatenate([y,z])

array([4, 5, 6, 7, 8, 9])

In [138]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
np.concatenate([x,y,z],axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
np.concatenate([x,y,z],axis=1)


AxisError: axis 1 is out of bounds for array of dimension 1

In [141]:
np.concatenate([x.reshape(1,3),y.reshape(1,3),z.reshape(1,3)],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

hem z hem y hem de z yi 1'e 3'lük matrislere döndürüp concat edilmesi yukarıdaki gibi olur. 

# 2D Matrix

In [142]:
a=np.random.randint(10,size=(2,3))
b=np.random.randint(10,size=(2,3))

In [143]:
a,b

(array([[6, 4, 8],
        [0, 0, 1]]),
 array([[7, 4, 9],
        [4, 4, 6]]))

In [144]:
np.concatenate([a,b])

array([[6, 4, 8],
       [0, 0, 1],
       [7, 4, 9],
       [4, 4, 6]])

In [145]:
np.concatenate([a,b],axis=1)

array([[6, 4, 8, 7, 4, 9],
       [0, 0, 1, 4, 4, 6]])

In [146]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

x,y

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]))

In [147]:
np.concatenate([x,y],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# Splitting of the Arrays

In [148]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [149]:
np.split(x,[3,6])

[array([1, 2, 3]), array([99, 99,  3]), array([2, 1])]

In [150]:
np.split(x,[3])

[array([1, 2, 3]), array([99, 99,  3,  2,  1])]

In [151]:
a,b,c=np.split(x,[3,5])

In [152]:
a

array([1, 2, 3])

In [153]:
b

array([99, 99])

In [154]:
c

array([3, 2, 1])

In [155]:
np.split(c,[4])

[array([3, 2, 1]), array([], dtype=int32)]

In [156]:
np.split(a,[4])

[array([1, 2, 3]), array([], dtype=int32)]

In [157]:
np.split(a,[2])

[array([1, 2]), array([3])]

In [158]:
np.split(x,4)

[array([1, 2]), array([ 3, 99]), array([99,  3]), array([2, 1])]

# 2D Matrix

In [159]:
m=np.arange(20).reshape(5,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [160]:
np.split(m,[1,3],axis=0)

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

# 2d matrix

In [161]:
m=np.arange(20).reshape(5,4)

In [162]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [163]:
np.split(m,[1,3],axis=0)

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [164]:
np.split(m,[1,3],axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [165]:
np.vsplit(m,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [166]:
np.hsplit(m,[1,3])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [167]:
upper,lower=np.split(m,[3])

In [168]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [169]:
lower

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [170]:
np.vsplit(m,[5])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([], shape=(0, 4), dtype=int32)]

In [171]:
np.vsplit(m,5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [172]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [173]:
np.hsplit(m,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [174]:
left,right=np.hsplit(m,2)

In [175]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [176]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

# Sorting of the Arrays

In [177]:
v=np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [178]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [179]:
v

array([2, 1, 4, 3, 5])

In [180]:
v.sort() #kalıcı bir değşim olmuş olur

In [181]:
v

array([1, 2, 3, 4, 5])

# 2d Matrix

In [182]:
twoD=np.random.randint(5,100,(3,3))
twoD

array([[36, 26, 71],
       [45, 17, 56],
       [63, 99,  5]])

In [183]:
np.sort(twoD,axis=0)
# the rows are sorted from upper to lower and column by column

array([[36, 17,  5],
       [45, 26, 56],
       [63, 99, 71]])

In [184]:
np.sort(twoD,axis=1)

#kendi içlerinde sırlama yapmışlar
# the columns are sorted from left to right and row by row

array([[26, 36, 71],
       [17, 45, 56],
       [ 5, 63, 99]])

# Numpy Indexing & Selection

In [185]:
arr=np.arange(0,11)

In [186]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Bracket Indexing & Selection

In [187]:
arr[8]

8

In [188]:
arr[-1]

10

In [189]:
arr[1:5]

array([1, 2, 3, 4])

In [190]:
arr[:5]

array([0, 1, 2, 3, 4])

In [191]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

# Indexing a 2D Array (Matrices)

In [192]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [193]:
arr_2d[1,1]

25

In [194]:
arr_2d[2]

array([35, 40, 45])

In [195]:
arr_2d[2,2]

45

# Slicing a 2D Array (Matrices)

In [196]:
print(arr_2d)

arr_2d[0:2,1:]

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


array([[10, 15],
       [25, 30]])

In [197]:
arr_2d[0:1,2:]

array([[15]])

In [198]:
arr_2d[2]

array([35, 40, 45])

In [199]:
arr_2d[:,1]

array([10, 25, 40])

In [200]:
arr_2d[1,1]=55

In [201]:
arr_2d

array([[ 5, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

In [202]:
arr_2d[1][1]=7.7
arr_2d

array([[ 5, 10, 15],
       [20,  7, 30],
       [35, 40, 45]])

# Fancy Indexing

In [203]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [204]:
v[1]

3

In [205]:
v[3]

9

In [206]:
index_list=[1,3,7]

In [207]:
v[index_list]

array([ 3,  9, 21])

In [208]:
v[[1,3,7]]

array([ 3,  9, 21])

In [209]:
v[[0,5,9]]

array([ 0, 15, 27])

In [210]:
arr_2d=np.zeros((10,10),dtype=int)

arr_2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [211]:
arr_2d.shape

(10, 10)

In [212]:
length_arr=arr_2d.shape[0]
length_arr

10

In [213]:
arr_2d[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [214]:
arr_2d[3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [215]:
for i in range(length_arr):
    arr_2d[i]=i
arr_2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [216]:
arr_2d[3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [217]:
arr_2d[[6,4,2,7]]

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

any_array[[row indices], [column indices]]

In [218]:
jj=np.arange(1,17).reshape(4,4)

In [219]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [220]:
jj[[1,2],[0,3]]

#row 1 column 2 
#row 

array([ 5, 12])

In [221]:
jj[1,2]

7

In [222]:
jj[[0,3],1]

array([ 2, 14])

# Using *Basic Slicing* & *Fancy Index* Together

In [223]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [224]:
jj[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [225]:
jj[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

In [226]:
jj[1:2,[1,2]]

array([[6, 7]])

In [227]:
jj[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

# More Indexing Help

In [228]:
arr=np.arange(1,11)

In [229]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [231]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [232]:
bool_arr=arr>4

In [233]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [234]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [235]:
arr[arr<4]

array([1, 2, 3])

In [236]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [238]:
(arr !=3) & (arr != 4)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [239]:
arr[(arr != 3 ) & (arr != 4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

In [244]:
con_arr=[]

for i in arr:
    if (i != 3) & (i != 4):
        con_arr.append(i)

print(con_arr)

[1, 2, 5, 6, 7, 8, 9, 10]


In [245]:
deneme=np.arange(1,15)

In [247]:
test=[]

for i in deneme:
    if (i > 5) & ( i!= 7 ):
        test.append(i)
print(test)

[6, 8, 9, 10, 11, 12, 13, 14]


In [248]:
fruits=["apple","orange","banana"]

In [249]:
len(fruits)

3

In [250]:
len(fruits[1])

6

In [251]:
fruits_1=[]

In [252]:
for i in fruits:
    if (len(i) > 5):
        fruits_1.append(i)

print(fruits_1)

['orange', 'banana']


In [254]:
if len(fruits[1])==5:
    print("True")
else:
    print("False")

False


# Broadcasting

In [255]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [256]:
arr[:5]

array([1, 2, 3, 4, 5])

In [257]:
arr[:5]=66

In [258]:
arr

array([66, 66, 66, 66, 66,  6,  7,  8,  9, 10])

In [259]:
a=[0,2,4,6,8,10]
a

[0, 2, 4, 6, 8, 10]

In [260]:
a[:3]=[100,100,100]

In [261]:
a

[100, 100, 100, 6, 8, 10]

In [262]:
arr=np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [263]:
slice_of_arr=arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [264]:
slice_of_arr[:]=99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [265]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [266]:
arr_copy=arr.copy()

In [267]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [268]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Numpy Operations

In [269]:
arr=np.arange(0,10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [270]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [271]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [272]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [273]:
import warnings

warnings.filterwarnings("ignore")

In [274]:
arr/arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [275]:
1/arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [277]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [278]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [279]:
arr+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [280]:
arr*1/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

# Universal Array Functions

In [281]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [283]:
np.subtract(arr,1)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [285]:
np.add(arr,2)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [286]:
np.subtract(arr,3)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [287]:
np.add(arr,2)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [288]:
np.divide(arr,2)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [290]:
np.divide(5,2)

2.5

In [292]:
np.divide(9,3)

3.0

In [289]:
np.multiply(arr,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [293]:
np.multiply(3,4)

12

In [294]:
np.power(arr,3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [295]:
np.mod(arr,2)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [296]:
np.absolute(-9)

9

In [297]:
np.absolute([-3,-5,4,6])

array([3, 5, 4, 6])

In [298]:
np.absolute(np.array([-3,-5,4,6]))

array([3, 5, 4, 6])

In [299]:
x1=np.arange(9.0).reshape(3,3)
x2=np.arange(3.0)

In [300]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [301]:
x2

array([0., 1., 2.])

In [302]:
np.subtract(x1,x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [303]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [304]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [305]:
np.max(arr)

9

In [306]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [307]:
np.sin(np.pi/2)

1.0

In [310]:
np.tan(np.pi/4)

0.9999999999999999

In [311]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [312]:
np.log10(1000)

3.0

# Statistical Calculations

np.amin(arr) This function determines the minimum value of the element along a specified axis.

np.amax(arr) This function determines the maximum value of the element along a specified axis.

arr.min() Returns minimum value of arr

arr.max(axis=0) Returns maximum value of specific axis

np.mean(arr, axis=0) It determines the mean value of the data set.

np.median(arr) It determines the median value of the data set.

np.std(arr, axis=1) It determines the standard deviation.

np.var(arr) It determines the variance.

np.ptp(arr) It returns a range of values (maximum - minimum) along an axis.

np.average(arr) It determines the weighted average.

np.percentile(arr) It determines the nth percentile of data along the specified axis.

np.corrcoef(arr) Returns correlation coefficient of array


In [313]:
v=np.array([1,1,2,2,3,3,3])
v

array([1, 1, 2, 2, 3, 3, 3])

In [314]:
np.mean(v)

2.142857142857143

In [315]:
v.mean()

2.142857142857143

In [316]:
np.median(v)

2.0

In [317]:
v.std()

0.8329931278350429

In [318]:
v.var()

0.6938775510204082

In [319]:
v.sum()

15

In [320]:
v.min()

1

In [321]:
np.ptp(v)  #pick to pick

2

In [322]:
np.random.seed(42)

xarr = np.random.randn(3, 5)
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783]])

In [323]:
np.corrcoef(xarr)

array([[ 1.        , -0.72342114, -0.20484812],
       [-0.72342114,  1.        ,  0.46728036],
       [-0.20484812,  0.46728036,  1.        ]])